In [5]:
import pandas as pd
pf=pd.read_excel('market equipment data of HealthCare.xlsx')

In [6]:
pf

,ptan,acceptsassignement,participationbegindate,businessname,practicename,practiceaddress1,practiceaddress2,practicecity,practicestate,practicezip9code,telephonenumber,specialitieslist,providertypelist,supplieslist,latitude,longitude,is_contracted_for_cba
0,339460094,False,2001-01-01,HANGER PROSTHETICS & ORTHOTICS EAST INC,HANGER CLINIC,308 E OAK ST,NaN,KISSIMMEE,FL,347444537,4078700111,MSC With Orthotic-Prosthetic|Orthotic Personnel,NaN,Neuromuscular Elect Stimulators (NMES)/Supplie...,28.30072,-81.40139,True
1,340220155,False,2001-01-01,HANGER PROSTHETICS & ORTHOTICS WEST INC,HANGER CLINIC,3303 N 75TH ST,NaN,SCOTTSDALE,AZ,852516402,4809451929,Orthotic Personnel|Prosthetic Personnel,NaN,Contracture Treatment Devices: Dynamic Splint|...,33.48631,-111.91947,True
2,414330433,False,1998-01-01,HANGER PROSTHETICS & ORTHOTICS INC,HANGER CLINIC,4543 EMPIRE CT,NaN,FREDERICKSBURG,VA,224081949,5408992655,Orthotic Personnel|Prosthetic Personnel,NaN,Orthoses: Custom Fabricated|Orthoses: Prefabri...,38.25118,-77.49287,True
3,339460145,False,2001-01-01,HANGER PROSTHETICS & ORTHOTICS EAST INC,HANGER CLINIC,694 ESSINGTON RD,NaN,JOLIET,IL,604354902,8157449944,MSC With Orthotic-Prosthetic|Orthotic Personnel,NaN,Neuromuscular Elect Stimulators (NMES)/Supplie...,41.53525,-88.16045,True
4,392420012,False,2004-01-01,"SCHECK & SIRESS PROSTHETICS, INC","SCHECK & SIRESS PROSTHETICS, INC.",1304 E 47TH ST,STE 204,CHICAGO,IL,606534508,3127575270,Orthotic Personnel|Prosthetic Personnel,NaN,Neuromuscular Elect Stimulators (NMES)/Supplie...,41.81967,-87.61978,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,397150022,True,2001-01-01,"HANNAFORD BROS. CO., LLC",HANNAFORD SUPERMARKET PHARMACY 8248,"HATCH PLAZA, ROUTE 25",NaN,PLYMOUTH,NH,32643729,6035363233,Pharmacy|Grocery Store,NaN,Epoetin|Immunosuppressive Drugs|Nebulizer Drug...,43.75030,-71.70334,False
1002,282933481,False,2020-03-01,WALGREEN CO,WALGREENS #6021,1620 N 59TH AVE,NaN,PHOENIX,AZ,850354985,6238492092,Pharmacy,NaN,Epoetin|Immunosuppressive Drugs|Infusion Drugs...,33.46658,-112.18708,False
1003,326910377,False,2014-01-01,APRIA HEALTHCARE LLC,APRIA HEALTHCARE LLC,2050 VISTA SEAVE 100-110,NaN,SALEM,OR,973021670,5034801100,Medical Supply Company Other|MSC With Respirat...,OXYGEN & EQUIPMENT,Automatic Ext Defibrillator (AEDS) and/or Supp...,44.90633,-123.04471,False
1004,282933855,False,2020-03-01,WALGREEN CO,WALGREENS #6654,149 DEMING ST,NaN,MANCHESTER,CT,60421731,8606441210,Pharmacy,NaN,Epoetin|Immunosuppressive Drugs|Infusion Drugs...,41.81259,-72.51477,False
1005,279610420,False,2019-01-01,WALMART INC,WAL-MART PHARMACY 10-0358,367 W CHERRY ST,NaN,ALMA,AR,729213408,4796324330,Pharmacy,NaN,Epoetin|Immunosuppressive Drugs|Infusion Drugs...,35.48044,-94.22786,False

In [7]:
p=pd.DataFrame(pf[['businessname','practicename','participationbegindate']])
p

,businessname,practicename,participationbegindate
0,HANGER PROSTHETICS & ORTHOTICS EAST INC,HANGER CLINIC,2001-01-01
1,HANGER PROSTHETICS & ORTHOTICS WEST INC,HANGER CLINIC,2001-01-01
2,HANGER PROSTHETICS & ORTHOTICS INC,HANGER CLINIC,1998-01-01
3,HANGER PROSTHETICS & ORTHOTICS EAST INC,HANGER CLINIC,2001-01-01
4,"SCHECK & SIRESS PROSTHETICS, INC","SCHECK & SIRESS PROSTHETICS, INC.",2004-01-01
...,...,...,...
1001,"HANNAFORD BROS. CO., LLC",HANNAFORD SUPERMARKET PHARMACY 8248,2001-01-01
1002,WALGREEN CO,WALGREENS #6021,2020-03-01
1003,APRIA HEALTHCARE LLC,APRIA HEALTHCARE LLC,2014-01-01
1004,WALGREEN CO,WALGREENS #6654,2020-03-01
1005,WALMART INC,WAL-MART PHARMACY 10-0358,2019-01-01

In [8]:
uniq=p.drop_duplicates()
uniq = uniq.groupby(by=["businessname",'participationbegindate'])['practicename'].unique().reset_index()
uniq

,businessname,participationbegindate,practicename
0,ABDAS ARTIFICIAL EYE AND FACIAL CENTER INC,1998-01-01,[ABDA'S ARTIFICIAL EYE & FACIAL CENT]
1,ACADIA HOME CARE,1998-01-01,[ROTECH]
2,ACCREDO HEALTH GROUP INC,2009-12-24,[ACCREDO HEALTH GROUP INC]
3,"ADVANCED PROSTHETICS AND ORTHOTICS, INC.",1998-01-01,[ADVANCED PROSTHETICS & ORTHOTICS IN]
4,ALAN H UPCHURCH O D PC,1998-01-01,"[ALAN H UPCHURCH OD, PC]"
...,...,...,...
203,WESTFIELD PHARMACY INC,1998-01-01,[WESTFIELD PHARMACY INC]
204,"WHITE DRUG COMPANY OF JAMESTOWN, INC",1998-01-01,[THRIFTY WHITE PHARMACY #068]
205,WHITE DRUG ENTERPRISES INC,2011-05-06,"[THRIFTY WHITE PHARMACY #022, THRIFTY WHITE PH..."
206,WILLIAMS BROS HEALTH CARE PHARMACY INC,1998-01-01,[WILLIAMS BROS HEALTH CARE PHARMACY]
207,WRIGHT & FILIPPIS LLC,1998-01-01,"[WRIGHT & FILIPPIS, LLC, WRIGHT & FILIPPIS LLC..."

In [9]:
id=len(uniq['businessname'])
id

208

In [10]:
hospital_id=[]
for i in range(id):
    idn=500+i
    hospital_id.append(idn)
hospital_id

[500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707]

In [11]:
hospital_master=pd.DataFrame()
hospital_master['hospital_id']=hospital_id
hospital_master['hospital_name']=uniq['businessname']
hospital_master['practice_name']=uniq['practicename']
hospital_master['create_date']=uniq['participationbegindate']
hospital_master

,hospital_id,hospital_name,practice_name,create_date
0,500,ABDAS ARTIFICIAL EYE AND FACIAL CENTER INC,[ABDA'S ARTIFICIAL EYE & FACIAL CENT],1998-01-01
1,501,ACADIA HOME CARE,[ROTECH],1998-01-01
2,502,ACCREDO HEALTH GROUP INC,[ACCREDO HEALTH GROUP INC],2009-12-24
3,503,"ADVANCED PROSTHETICS AND ORTHOTICS, INC.",[ADVANCED PROSTHETICS & ORTHOTICS IN],1998-01-01
4,504,ALAN H UPCHURCH O D PC,"[ALAN H UPCHURCH OD, PC]",1998-01-01
...,...,...,...,...
203,703,WESTFIELD PHARMACY INC,[WESTFIELD PHARMACY INC],1998-01-01
204,704,"WHITE DRUG COMPANY OF JAMESTOWN, INC",[THRIFTY WHITE PHARMACY #068],1998-01-01
205,705,WHITE DRUG ENTERPRISES INC,"[THRIFTY WHITE PHARMACY #022, THRIFTY WHITE PH...",2011-05-06
206,706,WILLIAMS BROS HEALTH CARE PHARMACY INC,[WILLIAMS BROS HEALTH CARE PHARMACY],1998-01-01
207,707,WRIGHT & FILIPPIS LLC,"[WRIGHT & FILIPPIS, LLC, WRIGHT & FILIPPIS LLC...",1998-01-01

In [12]:
p=pd.DataFrame(pf[['businessname','practicename','practiceaddress1','practiceaddress2','practicecity','practicestate','practicezip9code','telephonenumber']])
p

,businessname,practicename,practiceaddress1,practiceaddress2,practicecity,practicestate,practicezip9code,telephonenumber
0,HANGER PROSTHETICS & ORTHOTICS EAST INC,HANGER CLINIC,308 E OAK ST,NaN,KISSIMMEE,FL,347444537,4078700111
1,HANGER PROSTHETICS & ORTHOTICS WEST INC,HANGER CLINIC,3303 N 75TH ST,NaN,SCOTTSDALE,AZ,852516402,4809451929
2,HANGER PROSTHETICS & ORTHOTICS INC,HANGER CLINIC,4543 EMPIRE CT,NaN,FREDERICKSBURG,VA,224081949,5408992655
3,HANGER PROSTHETICS & ORTHOTICS EAST INC,HANGER CLINIC,694 ESSINGTON RD,NaN,JOLIET,IL,604354902,8157449944
4,"SCHECK & SIRESS PROSTHETICS, INC","SCHECK & SIRESS PROSTHETICS, INC.",1304 E 47TH ST,STE 204,CHICAGO,IL,606534508,3127575270
...,...,...,...,...,...,...,...,...
1001,"HANNAFORD BROS. CO., LLC",HANNAFORD SUPERMARKET PHARMACY 8248,"HATCH PLAZA, ROUTE 25",NaN,PLYMOUTH,NH,32643729,6035363233
1002,WALGREEN CO,WALGREENS #6021,1620 N 59TH AVE,NaN,PHOENIX,AZ,850354985,6238492092
1003,APRIA HEALTHCARE LLC,APRIA HEALTHCARE LLC,2050 VISTA SEAVE 100-110,NaN,SALEM,OR,973021670,5034801100
1004,WALGREEN CO,WALGREENS #6654,149 DEMING ST,NaN,MANCHESTER,CT,60421731,8606441210
1005,WALMART INC,WAL-MART PHARMACY 10-0358,367 W CHERRY ST,NaN,ALMA,AR,729213408,4796324330

In [13]:
branch=pd.merge(left=hospital_master[['hospital_name','hospital_id']],right=p,left_on=hospital_master['hospital_name'],right_on=p['businessname'])\
.drop(['key_0','hospital_name','businessname'],axis=1,)
branch

,hospital_id,practicename,practiceaddress1,practiceaddress2,practicecity,practicestate,practicezip9code,telephonenumber
0,500,ABDA'S ARTIFICIAL EYE & FACIAL CENT,1111 VETERANS MEMORIAL BLVD,STE 4,KENNER,LA,700624103,5044693937
1,501,ROTECH,108 MAIN ST,STE 2,PRESQUE ISLE,ME,47692871,2077641700
2,502,ACCREDO HEALTH GROUP INC,2825 W PERIMETER ROAD,SUITE 112,INDIANAPOLIS,IN,462413614,8008706419
3,503,ADVANCED PROSTHETICS & ORTHOTICS IN,50 MAPLE PL,NaN,MANHASSET,NY,110301927,5163657225
4,504,"ALAN H UPCHURCH OD, PC",3705 ELDORADO PKWY,NaN,MCKINNEY,TX,750704229,9725420331
...,...,...,...,...,...,...,...,...
1001,707,WRIGHT & FILIPPIS LLC,2845 CROOKS RD,NaN,ROCHESTER HILLS,MI,483093661,2488298241
1002,707,WRIGHT & FILIPPIS LLC,4201 SAINT ANTOINE ST,NaN,DETROIT,MI,482012153,3138325020
1003,707,WRIGHT & FILIPPIS INC,"1370 N MAIN ST,",SUITE A,LAPEER,MI,484461349,8106641101
1004,707,WRIGHT & FILIPPIS LLC,363 FREMONT ST,STE 300,BATTLE CREEK,MI,490173391,2699795760
1005,707,WRIGHT & FILIPPIS LLC,1604 STONE ST,NaN,PORT HURON,MI,480603344,8103856330

In [14]:
id=len(branch['practicename'])
branch_id=[]
for i in range(id):
    idn=1500+i
    branch_id.append(idn)
branch_id

[1500,
 1501,
 1502,
 1503,
 1504,
 1505,
 1506,
 1507,
 1508,
 1509,
 1510,
 1511,
 1512,
 1513,
 1514,
 1515,
 1516,
 1517,
 1518,
 1519,
 1520,
 1521,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 1529,
 1530,
 1531,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 1547,
 1548,
 1549,
 1550,
 1551,
 1552,
 1553,
 1554,
 1555,
 1556,
 1557,
 1558,
 1559,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1566,
 1567,
 1568,
 1569,
 1570,
 1571,
 1572,
 1573,
 1574,
 1575,
 1576,
 1577,
 1578,
 1579,
 1580,
 1581,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 1590,
 1591,
 1592,
 1593,
 1594,
 1595,
 1596,
 1597,
 1598,
 1599,
 1600,
 1601,
 1602,
 1603,
 1604,
 1605,
 1606,
 1607,
 1608,
 1609,
 1610,
 1611,
 1612,
 1613,
 1614,
 1615,
 1616,
 1617,
 1618,
 1619,
 1620,
 1621,
 1622,
 1623,
 1624,
 1625,
 1626,
 1627,
 1628,
 1629,
 1630,
 1631,
 1632,
 1633,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1648,
 1649,
 1650,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1657,
 1658,
 1659,
 1660,
 1661,
 1662,
 1663,
 1664,
 1665,
 1666,
 1667,
 1668,
 1669,
 1670,
 1671,
 1672,
 1673,
 1674,
 1675,
 1676,
 1677,
 1678,
 1679,
 1680,
 1681,
 1682,
 1683,
 1684,
 1685,
 1686,
 1687,
 1688,
 1689,
 1690,
 1691,
 1692,
 1693,
 1694,
 1695,
 1696,
 1697,
 1698,
 1699,
 1700,
 1701,
 1702,
 1703,
 1704,
 1705,
 1706,
 1707,
 1708,
 1709,
 1710,
 1711,
 1712,
 1713,
 1714,
 1715,
 1716,
 1717,
 1718,
 1719,
 1720,
 1721,
 1722,
 1723,
 1724,
 1725,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1732,
 1733,
 1734,
 1735,
 1736,
 1737,
 1738,
 1739,
 1740,
 1741,
 1742,
 1743,
 1744,
 1745,
 1746,
 1747,
 1748,
 1749,
 1750,
 1751,
 1752,
 1753,
 1754,
 1755,
 1756,
 1757,
 1758,
 1759,
 1760,
 1761,
 1762,
 1763,
 1764,
 1765,
 1766,
 1767,
 1768,
 1769,
 1770,
 1771,
 1772,
 1773,
 1774,
 1775,
 1776,
 1777,
 1778,
 1779,
 1780,
 1781,
 1782,
 1783,
 1784,
 1785,
 1786,
 1787,
 1788,
 1789,
 1790,
 1791,
 1792,
 1793,
 1794,
 1795,
 1796,
 1797,
 1798,
 1799,
 1800,
 1801,
 1802,
 1803,
 1804,
 1805,
 1806,
 1807,
 1808,
 1809,
 1810,
 1811,
 1812,
 1813,
 1814,
 1815,
 1816,
 1817,
 1818,
 1819,
 1820,
 1821,
 1822,
 1823,
 1824,
 1825,
 1826,
 1827,
 1828,
 1829,
 1830,
 1831,
 1832,
 1833,
 1834,
 1835,
 1836,
 1837,
 1838,
 1839,
 1840,
 1841,
 1842,
 1843,
 1844,
 1845,
 1846,
 1847,
 1848,
 1849,
 1850,
 1851,
 1852,
 1853,
 1854,
 1855,
 1856,
 1857,
 1858,
 1859,
 1860,
 1861,
 1862,
 1863,
 1864,
 1865,
 1866,
 1867,
 1868,
 1869,
 1870,
 1871,
 1872,
 1873,
 1874,
 1875,
 1876,
 1877,
 1878,
 1879,
 1880,
 1881,
 1882,
 1883,
 1884,
 1885,
 1886,
 1887,
 1888,
 1889,
 1890,
 1891,
 1892,
 1893,
 1894,
 1895,
 1896,
 1897,
 1898,
 1899,
 1900,
 1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 1910,
 1911,
 1912,
 1913,
 1914,
 1915,
 1916,
 1917,
 1918,
 1919,
 1920,
 1921,
 1922,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1930,
 1931,
 1932,
 1933,
 1934,
 1935,
 1936,
 1937,
 1938,
 1939,
 1940,
 1941,
 1942,
 1943,
 1944,
 1945,
 1946,
 1947,
 1948,
 1949,
 1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040,
 2041,
 2042,
 2043,
 2044,
 2045,
 2046,
 2047,
 2048,
 2049,
 2050,
 2051,
 2052,
 2053,
 2054,
 2055,
 2056,
 2057,
 2058,
 2059,
 2060,
 2061,
 2062,
 2063,
 2064,
 2065,
 2066,
 2067,
 2068,
 2069,
 2070,
 2071,
 2072,
 2073,
 2074,
 2075,
 2076,
 2077,
 2078,
 2079,
 2080,
 2081,
 2082,
 2083,
 2084,
 2085,
 2086,
 2087,
 2088,
 2089,
 2090,
 2091,
 2092,
 2093,
 2094,
 2095,
 2096,
 2097,
 2098,
 2099,
 2100,
 2101,
 2102,
 2103,
 2104,
 2105,
 2106,
 2107,
 2108,
 2109,
 2110,
 2111,
 2112,
 2113,
 2114,
 2115,
 2116,
 2117,
 2118,
 2119,
 2120,
 2121,
 2122,
 2123,
 2124,
 2125,
 2126,
 2127,
 2128,
 2129,
 2130,
 2131,
 2132,
 2133,
 2134,
 2135,
 2136,
 2137,
 2138,
 2139,
 2140,
 2141,
 2142,
 2143,
 2144,
 2145,
 2146,
 2147,
 2148,
 2149,
 2150,
 2151,
 2152,
 2153,
 2154,
 2155,
 2156,
 2157,
 2158,
 2159,
 2160,
 2161,
 2162,
 2163,
 2164,
 2165,
 2166,
 2167,
 2168,
 2169,
 2170,
 2171,
 2172,
 2173,
 2174,
 2175,
 2176,
 2177,
 2178,
 2179,
 2180,
 2181,
 2182,
 2183,
 2184,
 2185,
 2186,
 2187,
 2188,
 2189,
 2190,
 2191,
 2192,
 2193,
 2194,
 2195,
 2196,
 2197,
 2198,
 2199,
 2200,
 2201,
 2202,
 2203,
 2204,
 2205,
 2206,
 2207,
 2208,
 2209,
 2210,
 2211,
 2212,
 2213,
 2214,
 2215,
 2216,
 2217,
 2218,
 2219,
 2220,
 2221,
 2222,
 2223,
 2224,
 2225,
 2226,
 2227,
 2228,
 2229,
 2230,
 2231,
 2232,
 2233,
 2234,
 2235,
 2236,
 2237,
 2238,
 2239,
 2240,
 2241,
 2242,
 2243,
 2244,
 2245,
 2246,
 2247,
 2248,
 2249,
 2250,
 2251,
 2252,
 2253,
 2254,
 2255,
 2256,
 2257,
 2258,
 2259,
 2260,
 2261,
 2262,
 2263,
 2264,
 2265,
 2266,
 2267,
 2268,
 2269,
 2270,
 2271,
 2272,
 2273,
 2274,
 2275,
 2276,
 2277,
 2278,
 2279,
 2280,
 2281,
 2282,
 2283,
 2284,
 2285,
 2286,
 2287,
 2288,
 2289,
 2290,
 2291,
 2292,
 2293,
 2294,
 2295,
 2296,
 2297,
 2298,
 2299,
 2300,
 2301,
 2302,
 2303,
 2304,
 2305,
 2306,
 2307,
 2308,
 2309,
 2310,
 2311,
 2312,
 2313,
 2314,
 2315,
 2316,
 2317,
 2318,
 2319,
 2320,
 2321,
 2322,
 2323,
 2324,
 2325,
 2326,
 2327,
 2328,
 2329,
 2330,
 2331,
 2332,
 2333,
 2334,
 2335,
 2336,
 2337,
 2338,
 2339,
 2340,
 2341,
 2342,
 2343,
 2344,
 2345,
 2346,
 2347,
 2348,
 2349,
 2350,
 2351,
 2352,
 2353,
 2354,
 2355,
 2356,
 2357,
 2358,
 2359,
 2360,
 2361,
 2362,
 2363,
 2364,
 2365,
 2366,
 2367,
 2368,
 2369,
 2370,
 2371,
 2372,
 2373,
 2374,
 2375,
 2376,
 2377,
 2378,
 2379,
 2380,
 2381,
 2382,
 2383,
 2384,
 2385,
 2386,
 2387,
 2388,
 2389,
 2390,
 2391,
 2392,
 2393,
 2394,
 2395,
 2396,
 2397,
 2398,
 2399,
 2400,
 2401,
 2402,
 2403,
 2404,
 2405,
 2406,
 2407,
 2408,
 2409,
 2410,
 2411,
 2412,
 2413,
 2414,
 2415,
 2416,
 2417,
 2418,
 2419,
 2420,
 2421,
 2422,
 2423,
 2424,
 2425,
 2426,
 2427,
 2428,
 2429,
 2430,
 2431,
 2432,
 2433,
 2434,
 2435,
 2436,
 2437,
 2438,
 2439,
 2440,
 2441,
 2442,
 2443,
 2444,
 2445,
 2446,
 2447,
 2448,
 2449,
 2450,
 2451,
 2452,
 2453,
 2454,
 2455,
 2456,
 2457,
 2458,
 2459,
 2460,
 2461,
 2462,
 2463,
 2464,
 2465,
 2466,
 2467,
 2468,
 2469,
 2470,
 2471,
 2472,
 2473,
 2474,
 2475,
 2476,
 2477,
 2478,
 2479,
 2480,
 2481,
 2482,
 2483,
 2484,
 2485,
 2486,
 2487,
 2488,
 2489,
 2490,
 2491,
 2492,
 2493,
 2494,
 2495,
 2496,
 2497,
 2498,
 2499,
 ...]

In [16]:
branch_m=pd.DataFrame()
branch_m['branch_id']=branch_id
branch_m['hospital_id']=branch['hospital_id']
branch_m['practicename']=branch['practicename']
branch_m['practiceaddress1']=branch['practiceaddress1']
branch_m['practiceaddress2']=branch['practiceaddress2']
branch_m['practicecity']=branch['practicecity']
branch_m['practicestate']=branch['practicestate']
branch_m['practicezip9code']=branch['practicezip9code']
branch_m['telephonenumber']=branch['telephonenumber']

branch_m

,branch_id,hospital_id,practicename,practiceaddress1,practiceaddress2,practicecity,practicestate,practicezip9code,telephonenumber
0,1500,500,ABDA'S ARTIFICIAL EYE & FACIAL CENT,1111 VETERANS MEMORIAL BLVD,STE 4,KENNER,LA,700624103,5044693937
1,1501,501,ROTECH,108 MAIN ST,STE 2,PRESQUE ISLE,ME,47692871,2077641700
2,1502,502,ACCREDO HEALTH GROUP INC,2825 W PERIMETER ROAD,SUITE 112,INDIANAPOLIS,IN,462413614,8008706419
3,1503,503,ADVANCED PROSTHETICS & ORTHOTICS IN,50 MAPLE PL,NaN,MANHASSET,NY,110301927,5163657225
4,1504,504,"ALAN H UPCHURCH OD, PC",3705 ELDORADO PKWY,NaN,MCKINNEY,TX,750704229,9725420331
...,...,...,...,...,...,...,...,...,...
1001,2501,707,WRIGHT & FILIPPIS LLC,2845 CROOKS RD,NaN,ROCHESTER HILLS,MI,483093661,2488298241
1002,2502,707,WRIGHT & FILIPPIS LLC,4201 SAINT ANTOINE ST,NaN,DETROIT,MI,482012153,3138325020
1003,2503,707,WRIGHT & FILIPPIS INC,"1370 N MAIN ST,",SUITE A,LAPEER,MI,484461349,8106641101
1004,2504,707,WRIGHT & FILIPPIS LLC,363 FREMONT ST,STE 300,BATTLE CREEK,MI,490173391,2699795760
1005,2505,707,WRIGHT & FILIPPIS LLC,1604 STONE ST,NaN,PORT HURON,MI,480603344,8103856330